# GitHub Actions workflow to run tests on Android.
name: "Android"

on: [push, pull_request]

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: "Test ${{ matrix.name }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Android 8-9"
            min-nal: 26
            max-nal: 28
          - name: "Android 10-11"
            min-nal: 29
            max-nal: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Run CI script"
        run: ./scripts/test
        env:
          ARCH: "android"
          MIN_NAL: "${{ matrix.min-nal }}"
          MAX_NAL: "${{ matrix.max-nal }}"
