name: macos_ci

on: [push, pull_request]

jobs:
  build-native:
    strategy:
      matrix:
        os: [macos-latest]
        compiler: [clang, gcc]
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    env:
      CC: ${{ matrix.compiler }}
      ARCH: native
    name: ${{ matrix.compiler }} - ${{ matrix.os }}
    steps:
    - name: Install packages for macos
      run: brew install automake
    - uses: actions/checkout@v2
    - name: Run CI script
      run: ./scripts/test
