# GitHub Actions workflow to run tests on a Solaris VM.
name: "Solaris"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # At 00:00 daily.

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: "Solaris"
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'libressl' || github.event_name != 'schedule' }}
    permissions:
      contents: read
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup"
        run: |
          sudo apt-get update
          sudo apt-get install -y automake autoconf libtool
          ./autogen.sh

      - name: "Build on VM"
        uses: vmactions/solaris-vm@v1
        with:
          prepare: |
            pkg install gcc make
          run: |
            MAKE=gmake ./configure
            gmake -j2 check || (cat tests/test-suite.log && exit 1)
